// @ts-nocheck
import { browser } from 'fumadocs-mdx/runtime/browser';
import type * as Config from '../source.config';

const create = browser<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>();
const browserCollections = {
  docs: create.doc("docs", {"index.mdx": () => import("../content/docs/index.mdx?collection=docs"), "react-native-qr-code-gen/changelog.mdx": () => import("../content/docs/react-native-qr-code-gen/changelog.mdx?collection=docs"), "react-native-qr-code-gen/customization.mdx": () => import("../content/docs/react-native-qr-code-gen/customization.mdx?collection=docs"), "react-native-qr-code-gen/index.mdx": () => import("../content/docs/react-native-qr-code-gen/index.mdx?collection=docs"), "react-native-qr-code-gen/installation.mdx": () => import("../content/docs/react-native-qr-code-gen/installation.mdx?collection=docs"), "react-native-qr-code-gen/presets.mdx": () => import("../content/docs/react-native-qr-code-gen/presets.mdx?collection=docs"), "react-native-qr-code-gen/usage.mdx": () => import("../content/docs/react-native-qr-code-gen/usage.mdx?collection=docs"), "rn-tajweed-verse/changelog.mdx": () => import("../content/docs/rn-tajweed-verse/changelog.mdx?collection=docs"), "rn-tajweed-verse/customization.mdx": () => import("../content/docs/rn-tajweed-verse/customization.mdx?collection=docs"), "rn-tajweed-verse/index.mdx": () => import("../content/docs/rn-tajweed-verse/index.mdx?collection=docs"), "rn-tajweed-verse/installation.mdx": () => import("../content/docs/rn-tajweed-verse/installation.mdx?collection=docs"), "rn-tajweed-verse/tajweed-rules.mdx": () => import("../content/docs/rn-tajweed-verse/tajweed-rules.mdx?collection=docs"), "rn-tajweed-verse/usage.mdx": () => import("../content/docs/rn-tajweed-verse/usage.mdx?collection=docs"), "rn-ui/changelog.mdx": () => import("../content/docs/rn-ui/changelog.mdx?collection=docs"), "rn-ui/index.mdx": () => import("../content/docs/rn-ui/index.mdx?collection=docs"), "rn-ui/installation.mdx": () => import("../content/docs/rn-ui/installation.mdx?collection=docs"), "rn-ui/theming.mdx": () => import("../content/docs/rn-ui/theming.mdx?collection=docs"), "rn-ui/components/avatar.mdx": () => import("../content/docs/rn-ui/components/avatar.mdx?collection=docs"), "rn-ui/components/badge.mdx": () => import("../content/docs/rn-ui/components/badge.mdx?collection=docs"), "rn-ui/components/bottom-sheet.mdx": () => import("../content/docs/rn-ui/components/bottom-sheet.mdx?collection=docs"), "rn-ui/components/button.mdx": () => import("../content/docs/rn-ui/components/button.mdx?collection=docs"), "rn-ui/components/card.mdx": () => import("../content/docs/rn-ui/components/card.mdx?collection=docs"), "rn-ui/components/form-field.mdx": () => import("../content/docs/rn-ui/components/form-field.mdx?collection=docs"), "rn-ui/components/index.mdx": () => import("../content/docs/rn-ui/components/index.mdx?collection=docs"), "rn-ui/components/select.mdx": () => import("../content/docs/rn-ui/components/select.mdx?collection=docs"), "rn-ui/components/toast.mdx": () => import("../content/docs/rn-ui/components/toast.mdx?collection=docs"), }),
};
export default browserCollections;