import type {
  Theme,
  ThemeColors,
  ThemeComponents,
  ThemeFonts,
  ThemeRadii,
  ThemeShadows,
  ThemeSpacing,
  ThemeTypography,
} from "./types";

export const fonts: ThemeFonts = {
  regular: undefined,
  medium: undefined,
  semibold: undefined,
  bold: undefined,
  mono: undefined,
};

export const spacing: ThemeSpacing = {
  none: 0,
  xxs: 2,
  xs: 4,
  sm: 8,
  md: 12,
  lg: 16,
  xl: 20,
  xxl: 24,
  xxxl: 32,
};

export const radii: ThemeRadii = {
  none: 0,
  xs: 4,
  sm: 8,
  md: 12,
  lg: 16,
  xl: 20,
  xxl: 28,
  full: 9999,
};

export const typography: ThemeTypography = {
  display: { fontSize: 44, lineHeight: 52, fontWeight: "700" },
  h1: { fontSize: 32, lineHeight: 40, fontWeight: "700" },
  h2: { fontSize: 28, lineHeight: 36, fontWeight: "700" },
  h3: { fontSize: 24, lineHeight: 32, fontWeight: "600" },
  title: { fontSize: 20, lineHeight: 28, fontWeight: "600" },
  subtitle: { fontSize: 16, lineHeight: 24, fontWeight: "600" },
  body: { fontSize: 16, lineHeight: 24, fontWeight: "400" },
  bodySmall: { fontSize: 14, lineHeight: 20, fontWeight: "400" },
  label: { fontSize: 14, lineHeight: 20, fontWeight: "600" },
  labelSmall: { fontSize: 12, lineHeight: 16, fontWeight: "600" },
  caption: { fontSize: 12, lineHeight: 16, fontWeight: "400" },
};

const shadows: ThemeShadows = {
  none: {
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0,
    shadowRadius: 0,
    elevation: 0,
  },
  sm: {
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0,
    shadowRadius: 0,
    elevation: 0,
  },
  md: {
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0,
    shadowRadius: 0,
    elevation: 0,
  },
  lg: {
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0,
    shadowRadius: 0,
    elevation: 0,
  },
};

const components: ThemeComponents = {
  borderWidth: {
    default: 1,
    strong: 1.25,
    focus: 1.5,
    ring: 2,
    hairline: 0.5,
  },
  button: {
    height: { xs: 30, sm: 36, md: 44, lg: 52, xl: 56 },
    paddingX: { xs: 10, sm: 12, md: 16, lg: 20, xl: 24 },
    iconSize: { xs: 14, sm: 16, md: 18, lg: 20, xl: 20 },
  },
  iconButton: {
    size: { sm: 32, md: 40, lg: 44 },
    iconSize: { sm: 16, md: 20, lg: 22 },
    badge: {
      size: 16,
      minWidth: 16,
      offset: -2,
      paddingX: 4,
      borderWidth: 1.5,
      fontSize: 8,
      lineHeight: 10,
    },
  },
  timeline: {
    indicatorSize: 12,
    connectorWidth: 1.25,
    connectorMinHeight: 32,
  },
  table: {
    minColumnWidth: 120,
  },
  metricCard: {
    iconSize: 20,
  },
  floatingActionButton: {
    size: { sm: 44, md: 52, lg: 60 },
    iconSize: { sm: 18, md: 22, lg: 24 },
    paddingX: { sm: 14, md: 18, lg: 22 },
  },
  switch: {
    width: { sm: 42, md: 50, lg: 58 },
    height: { sm: 24, md: 30, lg: 34 },
    thumbSize: { sm: 18, md: 22, lg: 26 },
    iconSize: { sm: 10, md: 12, lg: 14 },
  },
};

const lightColors: ThemeColors = {
  background: "#F8FAFC",
  backgroundMuted: "#F1F5F9",
  backgroundSubtle: "#E2E8F0",
  surface: "#FFFFFF",
  surfaceRaised: "#FFFFFF",
  surfaceMuted: "#F8FAFC",
  text: "#0F172A",
  textMuted: "#475569",
  textSubtle: "#94A3B8",
  textInverse: "#FFFFFF",
  primary: "#4F46E5",
  primarySoft: "#EEF2FF",
  primaryStrong: "#3730A3",
  onPrimary: "#FFFFFF",
  secondary: "#334155",
  secondarySoft: "#E2E8F0",
  onSecondary: "#FFFFFF",
  accent: "#F97316",
  accentSoft: "#FFEDD5",
  onAccent: "#FFFFFF",
  success: "#10B981",
  successSoft: "#D1FAE5",
  onSuccess: "#FFFFFF",
  warning: "#F59E0B",
  warningSoft: "#FEF3C7",
  onWarning: "#111827",
  danger: "#EF4444",
  dangerSoft: "#FEE2E2",
  onDanger: "#FFFFFF",
  info: "#0EA5E9",
  infoSoft: "#E0F2FE",
  onInfo: "#FFFFFF",
  border: "#CBD5E1",
  borderMuted: "#E2E8F0",
  divider: "#CBD5E1",
  input: "#FFFFFF",
  placeholder: "#94A3B8",
  disabled: "#E2E8F0",
  disabledText: "#94A3B8",
  overlay: "rgba(15, 23, 42, 0.48)",
  transparent: "transparent",
};

const darkColors: ThemeColors = {
  background: "#08111F",
  backgroundMuted: "#0F1B2D",
  backgroundSubtle: "#17243A",
  surface: "#0F1B2D",
  surfaceRaised: "#17243A",
  surfaceMuted: "#111827",
  text: "#F8FAFC",
  textMuted: "#CBD5E1",
  textSubtle: "#94A3B8",
  textInverse: "#0F172A",
  primary: "#818CF8",
  primarySoft: "#312E81",
  primaryStrong: "#A5B4FC",
  onPrimary: "#111827",
  secondary: "#CBD5E1",
  secondarySoft: "#334155",
  onSecondary: "#0F172A",
  accent: "#FB923C",
  accentSoft: "#431407",
  onAccent: "#111827",
  success: "#34D399",
  successSoft: "#064E3B",
  onSuccess: "#052E16",
  warning: "#FBBF24",
  warningSoft: "#451A03",
  onWarning: "#111827",
  danger: "#F87171",
  dangerSoft: "#450A0A",
  onDanger: "#111827",
  info: "#38BDF8",
  infoSoft: "#0C4A6E",
  onInfo: "#082F49",
  border: "#334155",
  borderMuted: "#1E293B",
  divider: "#334155",
  input: "#0F1B2D",
  placeholder: "#64748B",
  disabled: "#1E293B",
  disabledText: "#64748B",
  overlay: "rgba(0, 0, 0, 0.72)",
  transparent: "transparent",
};

export const lightTheme: Theme = {
  mode: "light",
  dark: false,
  colors: lightColors,
  fonts,
  typography,
  spacing,
  radii,
  shadows,
  components,
};

export const darkTheme: Theme = {
  mode: "dark",
  dark: true,
  colors: darkColors,
  fonts,
  typography,
  spacing,
  radii,
  shadows,
  components,
};

export const defaultThemes = {
  light: lightTheme,
  dark: darkTheme,
} as const;
